using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyHitCheck : MonoBehaviour
{
    public bool HitFLG;
    public GameObject bullet;

    void Start()
    {
        
    }

    void Update()
    {

    }

    //OnTrigger‚Å‚·‚è”²‚¯”»’è‚ğæ‚é
    private void OnTriggerEnter(Collider other)
    {
        //’e‚ÉÕ“Ë‚µ‚½‚Ìˆ—
        if (other.transform.tag == "PlayerAttack")
        {
            bullet = other.gameObject;

            HitFLG = true;
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.transform.tag == "PlayerAttack")
        {
            Destroy(other.gameObject);

            bullet = null;

            HitFLG = false;
        }
    }

    public void BulletDelete()
    {
        if(bullet != null)
        {
            Destroy(bullet);
            HitFLG = false;
        }
    }
}